name: biapy2
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - ipyvolume
  - pip
  - jupyterlab
  - ipywidgets
  - pyimagej
  - openjdk=8
  - plotnine
  - seaborn
  - napari
  - pip:
    - trackpy
    - tensorflow
    - tqdm
    - torch 
    - torchvision
    - mrc
    - stardist
    - cellpose
    - aicsimageio